// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocvdafekofkqkexjiqxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jdmRhZmVrb2ZrcWtleGppcXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQ1NDksImV4cCI6MjA1OTk3MDU0OX0.iVcr2NVNTDTVnD42Fl3ts-8cKs-O0ULdspWgwpC5f_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);